// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Page = 2,
  PageToken = 3,
  Panel = 4,
  PanelToken = 5,
  Sfx = 6,
  Line = 7,
  Source = 8,
  Style = 9,
  Content = 10,
  Ital = 11,
  Bold = 12,
  BoldItal = 13,
  Note = 14,
  Spread = 15,
  SpreadToken = 16
