// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Page = 2,
  PageToken = 3,
  Panel = 4,
  PanelToken = 5,
  Line = 6,
  Sfx = 7,
  Dialogue = 8,
  Source = 9,
  Style = 10,
  Content = 11,
  BlockText = 12,
  Ital = 13,
  Bold = 14,
  BoldItal = 15,
  Note = 16,
  Spread = 17,
  SpreadToken = 18
