// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
export const parser = Parser.deserialize({
  version: 12,
  states: "!dOVQPOOO[QPO'#C^OOQO'#Cb'#CbQVQPOOOaQPO,58xOOQO-E6`-E6`OlQPO'#C`OOQO'#Cc'#CcOqQPO1G.dOOQO,58z,58zOOQO-E6a-E6a",
  stateData: "|~OYOS~ORPO~OZSO~OTUORQaWQa~OZXO~OTUORQiWQi~O",
  goto: "mWPPXP]PagTQORTVSWQRORTRQWSRYW",
  nodeNames: "⚠ Script Page PageToken Panel PanelToken",
  maxTerm: 11,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "!S~RTXYbYZgpqbstl}!Ow~gOY~~lOZ~~qQR~OYlZ~l~|QT~OYwZ~w",
  tokenizers: [0],
  topRules: {"Script":[0,1]},
  tokenPrec: 0
})
