// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 13,
  states: "*bOQOPOOOYOPO'#C^O_OPO'#CoOOOO'#Cq'#CqQQOPOOOdOPO,58xOrOPO,59ZOOOO-E6o-E6oO!QOPO'#C`OOOO'#Cr'#CrO!VOPO1G.dO!eOPO1G.uO!sOPO,58zOOOO-E6p-E6pO#_OQO'#CcOOOO'#Ct'#CtO#dOPO'#CgO#rOPO'#CfO#}OQO'#CnO$SOPO'#CbO$XOPO'#CbOOOO'#Cs'#CsO$dOPO1G.fOOOO'#Cd'#CdO%OOPO,58}OOOO-E6r-E6rO%iOQO,59QO%pOPO,59QO%uOPO,59QOOOO,59Y,59YOOOO,58|,58|O%zOPO,58|OOOO-E6q-E6qO&POQO1G.iO&UOSO'#CjO&^OQO'#CkO&cOQO'#ClO&hOQO'#CmOOOO'#Cv'#CvO&mOWO'#CiOOOO'#Ci'#CiOOOO1G.l1G.lO%WOQO1G.lO'OOQO1G.lO'VOPO'#ChO'bOPO1G.lOOOO1G.h1G.hOOOO'#Ce'#CeO'jOPO7+$TOOOO'#Cu'#CuO'oOSO,59UO'zOQO,59VO(POQO,59WO(UOQO,59XOOOO-E6t-E6tOOOO,59T,59TOOOO7+$W7+$WO%WOQO7+$WO(ZOQO7+$WO(bOPO7+$WOOOO<<Go<<GoOOOO-E6s-E6sOOOO1G.p1G.pOOOO1G.q1G.qOOOO1G.r1G.rOOOO1G.s1G.sOOOO<<Gr<<GrO%WOQO<<GrO(gOQO<<GrOOOOAN=^AN=^O%WOQOAN=^OOOOG22xG22x",
  stateData: "(w~ORPOdQO~OmTO~OmUO~OTWORQadQakQa~OTWORcadcakca~Om[O~OTWORQidQikQi~OTWORcidcikci~OndOo^Os_O{bORSaTSadSakSa~OpgO~Os_OnZXtZXuZX~OnkOtlOujO~OpmO~OmnO~Oo^Os_O{bO~OndOo^Os_O{bORSiTSidSikSi~OqqOmVa~OpvOvrOxsOytOzuO~OnzO~P%WOu{O~Os_O~Om!OO~Op!PO~On!ROw!RO~Op!TO~Op!UO~Op!VO~Om!XOpvOxsOytOzuO~On!ZO~P%WOs_On[Xu[X~On!]Ou![O~Or!^O~On!ROv!`Ow!RO~Ox!aO~Oy!bO~Oz!cO~On!eO~P%WOu!fO~On!hO~P%WOdRvxyzpy~",
  goto: "$akPPlPpPvz!R!Uz!X!^!a!s!}!}!}zlP#Y#`#j#p#|$STROSXXTUYZTe[fSc[fRodRh^R!QqVa[dfR}lQyjS!Yz{S!d!Z![S!g!e!fR!i!haxjz{!Z![!e!f!hcvjwz{!Z![!e!f!hQSORVSQYTQZUT]YZQf[RpfU`[dfSi`|R|lQ!SrR!_!S`wjz{!Z![!e!f!hR!Ww",
  nodeNames: "⚠ Script Page PageToken Panel PanelToken Line Sfx SfxTranslation SfxSource Text Source Style Content BlockText Ital Bold BoldItal Note Spread SpreadToken",
  maxTerm: 43,
  skippedNodes: [0],
  repeatNodeCount: 6,
  tokenData: "1T~RkOX!vXY#lYZ$YZp!vpq#lqr&ars!vst&vtu)Xux!vxy,wyz-^z{-s{}!v}!O.S!O!P!v!P!Q/e!Q![)X![!]/z!]!c!v!c!})X!}#R!v#R#S0a#S#T!v#T#o)X#o$g!v$g~)X^!}SwSpYOY#ZZz#Z{#R#Z#S~#ZY#`SpYOY#ZZz#Z{#R#Z#S~#Z~#sVn~pYOX#ZXY#lZp#Zpq#lqz#Z{#R#Z#S~#Z_$aPmXwS!_!`$dU$gP!_!`$jU$mP!_!`$pU$sPYZ$vU$yVOX%`XY&TYp%`pq&Tqz%`{#R%`#S~%`U%cPYZ%fU%iP!_!`%lU%oP!_!`%rU%uP!_!`%xU%{PYZ&OU&TOvUU&WRXY&TYZ%fpq&T_&jS{PwSpYOY#ZZz#Z{#R#Z#S~#Z_'PWwSRPpYOY'iZs'ist(_tz'iz{(S{#R'i#R#S(S#S~'iZ'pURPpYOY'iZz'iz{(S{#R'i#R#S(S#S~'iP(XQRPOY(SZ~(SZ(hUdPRPpYOY(_Zz(_z{(z{#R(_#R#S(z#S~(_P)RQdPRPOY(zZ~(z_)bdwSsPpYOY#ZZp#Zpq*pqt#Ztu*puw#Zwx*pxz#Z{}#Z}!O*p!O!Q#Z!Q![*p![!c#Z!c!}*p!}#R#Z#R#S,V#S#T#Z#T#o*p#o$g#Z$g~*pZ*wdsPpYOY#ZZp#Zpq*pqt#Ztu*puw#Zwx*pxz#Z{}#Z}!O*p!O!Q#Z!Q![*p![!c#Z!c!}*p!}#R#Z#R#S,V#S#T#Z#T#o*p#o$g#Z$g~*pP,[XsPpq,Vtu,Vwx,V}!O,V!Q![,V!c!},V#R#S,V#T#o,V$g~,V_-QSwSqPpYOY#ZZz#Z{#R#Z#S~#Z_-gSwSrPpYOY#ZZz#Z{#R#Z#S~#ZZ-zPoPyYz{-}Y.SOzY_.]UTPwSpYOY.oZz.oz{/Y{#R.o#R#S/Y#S~.oZ.vUTPpYOY.oZz.oz{/Y{#R.o#R#S/Y#S~.oP/_QTPOY/YZ~/Y_/nStPwSpYOY#ZZz#Z{#R#Z#S~#Z_0TSuPwSpYOY#ZZz#Z{#R#Z#S~#ZZ0hXsPxYpq,Vtu,Vwx,V}!O,V!Q![,V!c!},V#R#S,V#T#o,V$g~,V",
  tokenizers: [0, 1, 2, 3],
  topRules: {"Script":[0,1]},
  tokenPrec: 352
})
